var GAME_LEVELS = [
  ["                                                                                ",
   "                                                             o                  ",
   "                                                             p                  ",
   "                                                           xxxxx                ",
   "                                                  o                             ",
   "                                                                                ",
   "                                            o                                   ",
   "                                 o o        o   xxxxxxxxxx                      ",
   "                                o   o      xx                                   ",
   "                                o    o                                          ",
   "                                o    xxx                                        ",
   "                                o                               o           xx  ",
   "  xx                          xxxx                              o            x  ",
   "  x                                                             o          o x  ",
   "  x           xxxxx                                          xxxxxx          x  ",
   "  x @                   a                                    x    x          x  ",
   "  xxxxxxx=   o                                               x    xxxx       x  ",
   "  xxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxx       xxxxxxxxx  ",
   "             x!!!!!x                            x!!!!!!!!!!x                    ",
   "             x!!!!!x                            x!!!!!!!!!!x                    ",
   "             xxxxxxx                            x!!!!!!!!!!x                    ",
   "                                                xxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                 ooo                                                       pxx!x  ",
   "                                                 xxx                                          xxxxxxxxxxxxxxx!!x  ",
   "                                                                                                !!!!!!!!!!!!!!xx  ",
   "                                                                                               vxxxxxxxxxxxxxxx   ",
   "                                              o                                                                   ",
   "                                              o                                     oo                            ",
   "                                         xxxxxxx    xx                             xxxx      xxx                  ",
   "                                               x     x                             x         x x                  ",
   "                                               x     xxxx                          x         x                    ",
   "                                               x     x                            xxx        x                    ",
   "                                             xxxx    x                             x         x                    ",
   "                                               x     x               x             x         x                    ",
   "                                               x     x               x             x         x                    ",
   "                                               x     x               x       xxxxxxxxx       x                    ",
   "                                       o            xx               x       x               x                    ",
   "     @                 xxxxxxx         a                             x       x               x                    ",
   "    xxx         o            xxxxx=                                  xxx     x               x                    ",
   "                             xxxxxxxxxxxxxxxxxxx     xxxxxxxxxxx     x     o x               x                    ",
   "!!!!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     x      xx               x                    ",
   "!!!!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                             x                    ",
   "!!!!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                             x                    ",
   "!!!!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     xxxxxxxxx       xxxx    x                    ",
   "!!!!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx ooo x!!!!!!!!!!!!!!!!!!x  o x                    ",
   "!!!!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx ooo x!!!!!!!!!!!!!!!!!!x  o x                    ",
   "!!!!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!xxxxxx                    "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                               o                              ",
   "                                                                               o                              ",
   "                                                                               o                              ",
   "                                                                              XXXX                            ",
   "                                                                                                              ",
   "                                                  xxx                 !!!!!!!!!               p               ",
   "                                                 xx!xx           o     xxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                                                xx!!!xx         xxx   v                       x               ",
   "                                                 xx!xx                                        x               ",
   "                                                   v                                          x               ",
   "                                                                                              x               ",
   "                                                            xx                                x               ",
   "                                                                                              x               ",
   "                                                                                                   x          ",
   "                                             o                                                     xx         ",
   "                                             x                                         ooo         x          ",
   "                                                     o                              xxxxxxxxxxxxxxxx          ",
   "                                                xx  xx                                                        ",
   "  xxx                               xxxxx                                                                xxx  ",
   "  x x                                                                                  o                 x x  ",
   "  x                                                                                   xxx                  x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x            xxxx       o   xxxx                                                                         x  ",
   "  x            xxxx       a                                xxxx                                            x  ",
   "  x      @     xxxx      xx                                                                                x  ",
   "  x      x     xxxx      xx                                                                                x  ",
   "  x      x     xxxx      xx                                                                           xxxxxx  ",
   "  x      x     xxxx!!!!!!xx                                                                              o x  ",
   "  xx!!!!!x!!!!!xxxx!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                      x  @  x                                 ",
   "                                                                      x     x                                 "],
  ["                                                                      x     x                                 ",
   "                                                                      x     x                                 ",
   "                                                                      x     x                                 ",
   "                                                                      x     xxxxxxxxx                         ",
   "                                                                      x  o                                    ",
   "                                        x=              o o           x         =                             ",
   "                                         xxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxx o o  xxxxx       ",
   "                                                                                                      x       ",
   "                                  o                                                                   x       ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                xxxxxxxx                                                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                o                                                                             ",
   "                           xxxxxxxxxx                                                                         ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                   o                          ",
   "                                                  o                x=                        x                ",
   "                                                                   xxxxxxxxxxxxxxxxxxxxxxxxxxx                ",
   "  x                                                                                                           ",
   "  x                                             xxxxxx                                                        ",
   "  x p                                                                                                    o  x ",
   "  xxxxxxx                                                                                              xxxxxx ",
   "        x =                                                                                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
